---
openapi: 3.0.3
info:
  title: SonataFlow Plans
  description: An application that can process plans
  version: 1.0.0-SNAPSHOT
servers:
  - url: http://localhost:9000
    description: Self
paths:
  /instruction:
    post:
      tags:
      - Service Resource
      operationId: getInstruction
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /purchases/purchase/{identifier}:
    get:
      tags:
      - Service Resource
      operationId: getPurchase
      parameters:
      - name: identifier
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /purchases/purchases:
    get:
      tags:
      - Service Resource
      operationId: getPurchases
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /shipments/shipments:
    get:
      tags:
      - Service Resource
      operationId: getShipments
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /log:
    post:
      tags:
      - Service Resource
      operationId: logMessage
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /instruction/{topic}:
    post:
      tags:
      - Service Resource
      operationId: setInstruction
      parameters:
      - name: topic
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: OK
  /instruction/{topic}/feedback:
    get:
      tags:
      - Service Resource
      operationId: getFeedback
      parameters:
      - name: topic
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /executeFunction/{name}:
    post:
      tags:
      - Service Resource
      operationId: executeFunction
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
